{
    'name': 'Interior Quotation Management',
    'version': '1.0.0',
    'summary': 'Quotation system for interior & plywood works',
    'description': 'Create project-style quotations with materials, labour, accessories and history/revisions.',
    'author': 'Generated by ChatGPT',
    'category': 'Sales',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'mail', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/interior_quotation_views.xml',
        'views/interior_menus.xml',
        'reports/quotation_reports.xml',
        'reports/report_header.xml',
        'reports/report_layout.xml',
    ],

    "assets": {
        "web.assets_frontend": [
            "/interior_quotation_management/static/src/css/report.scss",
        ]
    },

    'installable': True,
    'application': True,
    'auto_install': False,
}
